packages:
  - packages/*

catalog:
  '@ava/typescript': ^6.0.0
  '@babel/cli': ^7.28.3
  '@babel/core': ^7.28.4
  '@babel/plugin-syntax-jsx': ^7.27.1
  '@babel/preset-react': ^7.27.1
  '@eslint-react/eslint-plugin': ^2.0.3
  '@eslint/css': ^0.11.1
  '@eslint/js': ^9.37.0
  '@monorepo-utils/workspaces-to-typescript-project-references': ^2.11.0
  '@reflink/reflink': ^0.1.19
  '@rollup/plugin-alias': ^5.1.1
  '@rollup/plugin-babel': ^6.0.4
  '@rollup/plugin-commonjs': ^28.0.6
  '@rollup/plugin-node-resolve': ^16.0.1
  '@rollup/plugin-replace': ^6.0.2
  '@rollup/plugin-swc': ^0.4.0
  '@swc/core': ^1.13.5
  '@types/node': ^24.6.0
  '@types/react': ^19.2.0
  '@types/react-dom': ^19.2.0
  '@typescript-eslint/eslint-plugin': ^8.46.0
  '@typescript-eslint/parser': ^8.46.0
  ava: ^6.4.1
  babel-plugin-react-compiler: ^1.0.0
  eslint: ^9.37.0
  eslint-config-prettier: ^10.1.8
  eslint-config-turbo: ^2.5.8
  eslint-plugin-import-x: ^4.16.1
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^7.0.0
  expect-type: ^1.2.2
  globals: ^16.4.0
  option-t: ^55.1.0
  postcss: ^8.5.6
  postcss-import: ^16.1.1
  prettier: ^3.6.2
  react: ^19.2.0
  react-dom: ^19.2.0
  rollup: ^4.52.3
  tinyspy: ^4.0.4
  turbo: ^2.5.8
  typescript: ^5.9.3
  web-ext: ^8.10.0

minimumReleaseAge: 1440
