packages:
  - packages/*

minimumReleaseAge: 1440 # 60min * 24

catalog:
  "@ava/typescript": ^6.0.0
  "@babel/cli": ^7.28.3
  "@babel/core": ^7.28.4
  "@babel/plugin-syntax-jsx": ^7.27.1
  "@babel/preset-react": ^7.27.1
  "@eslint-react/eslint-plugin": ^1.53.1
  "@eslint/css": ^0.11.0
  "@eslint/js": ^9.35.0
  "@monorepo-utils/workspaces-to-typescript-project-references": ^2.11.0
  "@reflink/reflink": ^0.1.19
  "@rollup/plugin-alias": ^5.1.1
  "@rollup/plugin-babel": ^6.0.4
  "@rollup/plugin-commonjs": ^28.0.6
  "@rollup/plugin-node-resolve": ^16.0.1
  "@rollup/plugin-replace": ^6.0.2
  "@rollup/plugin-swc": ^0.4.0
  "@swc/core": ^1.13.5
  "@types/node": ^24.3.1
  "@types/react-dom": ^19.1.9
  "@types/react": ^19.1.12
  "@typescript-eslint/eslint-plugin": ^8.44.0
  "@typescript-eslint/parser": ^8.44.0
  ava: ^6.4.1
  babel-plugin-react-compiler: ^19.1.0-rc.3
  eslint-config-prettier: ^10.1.8
  eslint-config-turbo: ^2.5.6
  eslint-plugin-import-x: ^4.16.1
  eslint-plugin-react-hooks: ^6.0.0-rc.2
  eslint-plugin-react: ^7.37.5
  eslint: ^9.35.0
  expect-type: ^1.2.2
  globals: ^16.4.0
  jsdom: ^27.0.0
  option-t: ^55.1.0
  postcss-import: ^16.1.1
  postcss: ^8.5.6
  prettier: ^3.6.2
  react-dom: ^19.1.1
  react: ^19.1.1
  rollup: ^4.50.2
  tinyspy: ^4.0.3
  turbo: ^2.5.6
  typescript: ^5.9.2
  web-ext: ^8.9.0
