packages:
  - packages/*

catalog:
  '@ava/typescript': ^6.0.0
  '@babel/cli': ^7.28.3
  '@babel/core': ^7.28.5
  '@babel/plugin-syntax-jsx': ^7.27.1
  '@babel/preset-react': ^7.28.5
  '@eslint-react/eslint-plugin': ^2.3.13
  '@eslint/css': ^0.14.1
  '@eslint/js': ^9.39.2
  '@monorepo-utils/workspaces-to-typescript-project-references': ^2.11.0
  '@reflink/reflink': ^0.1.19
  '@rollup/plugin-alias': ^6.0.0
  '@rollup/plugin-babel': ^6.1.0
  '@rollup/plugin-commonjs': ^29.0.0
  '@rollup/plugin-node-resolve': ^16.0.3
  '@rollup/plugin-replace': ^6.0.3
  '@rollup/plugin-swc': ^0.4.0
  '@swc/core': ^1.15.4
  '@types/node': ^25.0.3
  '@types/react': ^19.2.7
  '@types/react-dom': ^19.2.3
  '@typescript-eslint/eslint-plugin': ^8.50.1
  '@typescript-eslint/parser': ^8.50.1
  '@typescript/native-preview': 7.0.0-dev.20251212.1
  ava: ^6.4.1
  babel-plugin-react-compiler: ^1.0.0
  eslint: ^9.39.1
  eslint-config-prettier: ^10.1.8
  eslint-config-turbo: ^2.6.3
  eslint-plugin-import-x: ^4.16.1
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^7.0.1
  expect-type: ^1.3.0
  globals: ^16.5.0
  option-t: ^55.1.0
  postcss: ^8.5.6
  postcss-import: ^16.1.1
  prettier: ^3.7.4
  react: ^19.2.3
  react-dom: ^19.2.3
  rollup: ^4.53.5
  tinyspy: ^4.0.4
  turbo: ^2.6.3
  typescript: ^5.9.3
  web-ext: ^9.2.0

minimumReleaseAge: 7200
minimumReleaseAgeExclude:
  - '@typescript/native-preview'
