name: Setup CI
description: Setup CI environment

runs:
    using: composite
    steps:
        - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e
          with:
              node-version: 23.x

        - name: Setup corepack
          shell: bash
          run: |
              make setup_corepack

        - name: Get package manager's cache directory
          id: npm-cache-dir
          shell: bash
          run: echo "dir=$(pnpm store path)" >> $GITHUB_OUTPUT

        - name: Get cache unique key
          id: npm-cache-key
          shell: bash
          run: echo "id=${{ hashFiles('**/pnpm-lock.yaml') }}" >> $GITHUB_OUTPUT

        - name: Restore dependency caches
          uses: actions/cache/restore@5a3ec84eff668545956fd18022155c47e93e2684
          id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
          with:
              path: ${{ steps.npm-cache-dir.outputs.dir }}
              # We use an exact match to avoid to store unnecessary dependencies in the later step.
              key: build-v1-${{ runner.os }}-node-pnpm-${{ steps.npm-cache-key.outputs.id }}

        - name: install dependencies
          shell: bash
          # We only cache `npm config get cache`, not including `node_modules/`.
          # thus we need to do `npm ci` to restore `node_modules/` so we need run always this step.
          # if: steps.npm-cache.outputs.cache-hit != 'true''
          run: |
              make install

        - name: Save dependency caches
          uses: actions/cache/save@5a3ec84eff668545956fd18022155c47e93e2684
          # We run this step only on _trunk_ to aim to improve a cache hit.
          # For example, dependabot's pull requests sometimes shoot down a cache hit ratio
          # by changing a lock file with multiple variants.
          # Then we cannot reuse cache ideally because the lockfile is changed high frequently under such situation.
          # Cache utilization is down.
          # So we give up to save the cache on each of pull requests.
          if: ${{ (steps.npm-cache.outputs.cache-hit != 'true') && (github.ref == 'refs/heads/main') }}
          with:
              path: ${{ steps.npm-cache-dir.outputs.dir }}
              key: build-v1-${{ runner.os }}-node-pnpm-${{ steps.npm-cache-key.outputs.id }}
